# Generated by Django 5.1.5 on 2025-01-27 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyutor', '0003_alter_tyutorprofil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyutorprofil',
            name='fakultet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tyutor.fakultet'),
            preserve_default=False,
        ),
    ]
