# Generated by Django 5.1.5 on 2025-01-29 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyutor', '0004_alter_tyutorprofil_fakultet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topshiriq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fayl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('file', models.FileField(upload_to='topshiriq/')),
                ('topshiriq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fayls', to='tyutor.topshiriq')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
