# Generated by Django 5.1.5 on 2025-01-24 18:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tyutorprofil_delete_asosiy_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyutorprofil',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
