# Generated by Django 4.2.4 on 2023-08-18 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba_bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Talaba_nomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolim', models.CharField(blank=True, max_length=100)),
                ('tur_nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba.talaba_bolim')),
            ],
        ),
        migrations.CreateModel(
            name='Talaba_malumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField(blank=True, null=True)),
                ('fayl', models.FileField(blank=True, upload_to='malumot/')),
                ('bolim_nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba.talaba_nomi')),
            ],
        ),
    ]
