# Generated by Django 4.2.16 on 2024-09-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rahbariyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(blank=True, max_length=255)),
                ('lavozim', models.CharField(blank=True, max_length=255)),
                ('rasm', models.FileField(blank=True, upload_to='rahbariyat/')),
                ('nomer', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
