# Generated by Django 4.2.4 on 2023-11-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rahbariyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=255)),
                ('lavozim', models.CharField(max_length=255)),
                ('rasm', models.ImageField(upload_to='rahbariyat/')),
            ],
        ),
    ]
