# Generated by Django 4.2.4 on 2023-11-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rahbariyat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rahbariyat',
            name='fish',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rahbariyat',
            name='lavozim',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rahbariyat',
            name='rasm',
            field=models.ImageField(blank=True, upload_to='rahbariyat/'),
        ),
    ]
