# Generated by Django 4.2.16 on 2024-09-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yangilik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('body', models.TextField(blank=True, null=True)),
                ('rasm', models.FileField(blank=True, upload_to='yangilik/')),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
