# Generated by Django 4.2.16 on 2024-09-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abiturient_bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Abiturient_malumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolim_nomi', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField(blank=True, null=True)),
                ('fayl', models.FileField(blank=True, upload_to='malumot/')),
            ],
        ),
        migrations.CreateModel(
            name='Abiturient_nomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur_nomi', models.CharField(blank=True, max_length=100)),
                ('bolim', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
