# Generated by Django 4.2.4 on 2023-08-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inistitut_kengashi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(blank=True, max_length=100)),
                ('f_i_sh', models.CharField(blank=True, max_length=100)),
                ('telefon', models.CharField(blank=True, max_length=100)),
                ('malumot', models.TextField(blank=True, null=True)),
                ('rasm', models.FileField(blank=True, upload_to='institut_kengashi/')),
            ],
        ),
        migrations.CreateModel(
            name='Institut_haqida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(blank=True, max_length=100)),
                ('malumot', models.TextField(blank=True, null=True)),
                ('rasm', models.FileField(blank=True, upload_to='institut_haqida/')),
            ],
        ),
        migrations.CreateModel(
            name='Institut_tuzulmasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(blank=True, max_length=100)),
                ('malumot', models.TextField(blank=True, null=True)),
                ('rasm', models.FileField(blank=True, upload_to='institut_haqida/')),
            ],
        ),
        migrations.CreateModel(
            name='Qabulxona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('telefon', models.CharField(blank=True, max_length=100)),
                ('xabar', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rekvizidlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(blank=True, max_length=100)),
                ('okonx', models.CharField(blank=True, max_length=100)),
                ('shxr', models.CharField(blank=True, max_length=100)),
                ('royhatdan_otgan_sana', models.CharField(blank=True, max_length=100)),
                ('manzil', models.CharField(blank=True, max_length=100)),
                ('telefon', models.CharField(blank=True, max_length=100)),
                ('fax', models.CharField(blank=True, max_length=100)),
                ('gaznachi_hisob', models.CharField(blank=True, max_length=100)),
                ('gaznachi_inn', models.CharField(blank=True, max_length=100)),
                ('mfo', models.CharField(blank=True, max_length=100)),
                ('ifut', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
