# Generated by Django 4.2.4 on 2023-09-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jadval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(blank=True, max_length=100)),
                ('fakultet', models.CharField(blank=True, max_length=100)),
                ('yonalish', models.CharField(blank=True, max_length=100)),
                ('kurs', models.CharField(blank=True, max_length=100)),
                ('rasm', models.FileField(blank=True, upload_to='jadval-rasm/')),
            ],
        ),
    ]
