# Generated by Django 4.2.16 on 2024-09-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakultet_talim_turi_id', models.CharField(max_length=10)),
                ('fakultet', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jadval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(blank=True, max_length=10)),
                ('fakultet', models.CharField(blank=True, max_length=10)),
                ('yonalish', models.CharField(blank=True, max_length=10)),
                ('kurs', models.CharField(blank=True, max_length=10)),
                ('rasm', models.FileField(blank=True, upload_to='jadval/')),
            ],
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs_talim_turi_id', models.CharField(max_length=10)),
                ('kurs_fakultet_id', models.CharField(max_length=10)),
                ('kurs_yonalish_id', models.CharField(max_length=10)),
                ('kurs', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Talim_turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talim_turi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yonalish_talim_turi_id', models.CharField(max_length=10)),
                ('yonalish_fakultet_id', models.CharField(max_length=10)),
                ('yonalish', models.CharField(max_length=100)),
            ],
        ),
    ]
