# Generated by Django 4.2.4 on 2023-10-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadval', '0002_fakultet_kurs_talim_turi_yonalish'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakultet',
            name='fakultet_talim_turi_id',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kurs',
            name='kurs_fakultet_id',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kurs',
            name='kurs_talim_turi_id',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kurs',
            name='kurs_yonalish_id',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yonalish',
            name='yonalish_fakultet_id',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yonalish',
            name='yonalish_talim_turi_id',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
