# Generated by Django 4.2.4 on 2023-10-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadval', '0003_fakultet_fakultet_talim_turi_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadval',
            name='qrcode',
            field=models.FileField(blank=True, upload_to='qrcode-rasm/'),
        ),
        migrations.AlterField(
            model_name='jadval',
            name='fakultet',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='jadval',
            name='kurs',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='jadval',
            name='turi',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='jadval',
            name='yonalish',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
