# Generated by Django 4.2.4 on 2023-11-15 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jadval', '0004_jadval_qrcode_alter_jadval_fakultet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadval',
            name='qrcode',
        ),
    ]
