# Generated by Django 4.2.4 on 2023-11-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadval', '0005_remove_jadval_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadval',
            name='fakultet',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jadval',
            name='kurs',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jadval',
            name='turi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jadval',
            name='yonalish',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
