# Generated by Django 4.2.4 on 2023-11-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadval', '0006_alter_jadval_fakultet_alter_jadval_kurs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadval',
            name='fakultet',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='jadval',
            name='kurs',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='jadval',
            name='rasm',
            field=models.FileField(blank=True, upload_to='jadval/'),
        ),
        migrations.AlterField(
            model_name='jadval',
            name='turi',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='jadval',
            name='yonalish',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
