# Generated by Django 4.2.4 on 2023-08-18 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rahbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lavozim', models.CharField(blank=True, max_length=100)),
                ('darajasi', models.CharField(blank=True, max_length=100)),
                ('f_i_sh', models.CharField(blank=True, max_length=100)),
                ('telefon', models.CharField(blank=True, max_length=100)),
                ('malumot', models.TextField(blank=True, null=True)),
                ('rasm', models.FileField(blank=True, upload_to='rahbarlar/')),
                ('bolim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuzilma.bolim')),
                ('yonalish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuzilma.yonalish')),
            ],
        ),
    ]
