# Generated by Django 4.2.16 on 2024-09-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolim_nomi', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rahbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yonalish_id', models.CharField(blank=True, max_length=100)),
                ('bolim_id', models.CharField(blank=True, max_length=100)),
                ('lavozim', models.CharField(blank=True, max_length=100)),
                ('darajasi', models.CharField(blank=True, max_length=100)),
                ('f_i_sh', models.CharField(blank=True, max_length=100)),
                ('telefon', models.CharField(blank=True, max_length=100)),
                ('malumot', models.TextField(blank=True, null=True)),
                ('rasm', models.FileField(blank=True, upload_to='rahbarlar/')),
            ],
        ),
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yonalish_nomi', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
