# Generated by Django 4.2.4 on 2023-08-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuzilma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rahbar',
            name='bolim_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rahbar',
            name='yonalish_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
