# Generated by Django 4.2.4 on 2023-08-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuzilma', '0002_alter_rahbar_bolim_id_alter_rahbar_yonalish_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bolim',
            old_name='nomi',
            new_name='bolim_nomi',
        ),
        migrations.RenameField(
            model_name='yonalish',
            old_name='nomi',
            new_name='yonalish_nomi',
        ),
    ]
