# Generated by Django 4.2.16 on 2024-09-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QabulAriza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familya', models.CharField(blank=True, max_length=255)),
                ('ism', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('nomer', models.CharField(blank=True, max_length=255)),
                ('tahsil_olgan', models.CharField(blank=True, max_length=255)),
                ('fuqaroligi', models.CharField(blank=True, max_length=255)),
                ('telegram_name', models.CharField(blank=True, max_length=255)),
                ('wahatsap_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
